apiVersion: v1
kind: Pod
metadata:
  name: server-user-pod
  labels:
    name: server-user-pod
    app: nodejs-glc-docker-kubernetes
spec:
  containers:
    - name: server-user-pod
      image: luuphuc/ubuntu-nodejs
      ports:
        - containerPort: 8070
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
