apiVersion: v1
kind: Service
metadata:
  name: server-user-pod
  labels:
    name: server-user-pod
    app: nodejs-glc-docker-kubernetes

spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    name: server-user-pod
    app: nodejs-glc-docker-kubernetes
