apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2023-08-22T08:05:47Z"
  labels:
    node-app: ""
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:node-app: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":80,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: GoogleCloudConsole
      operation: Update
      time: "2023-08-22T08:05:47Z"
  name: nodejs-gke-service
  namespace: default
  resourceVersion: "1016252"
  uid: 76f08114-1c76-48d8-a6df-79a561574d5e
spec:
  clusterIP: 34.118.232.154
  clusterIPs:
    - 34.118.232.154
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    node-app: ""
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
